version: '3.8'

services:
  user_service:
    build:
      context: ./user_service
    ports:
      - "8001:80"
    networks:
      - app-network

  product_service:
    build:
      context: ./product_service
    ports:
      - "8002:80"
    networks:
      - app-network

  order_service:
    build:
      context: ./order_service      # ✅ HARUS pakai 'context:'
    ports:
      - "8003:80"
    depends_on:
      - user_service
      - product_service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
